# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bid.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import loan_payment_pb2 as loan__payment__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbid.proto\x12\x10nanoswap.message\x1a\x12loan_payment.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n\x03\x42id\x12\x16\n\x0elending_amount\x18\x01 \x01(\x03\x12\x39\n\x12repayment_schedule\x18\x02 \x03(\x0b\x32\x1d.nanoswap.message.LoanPayment\x12\x30\n\x0coffer_expiry\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x0btransaction\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x05 \x01(\x08\x42\x0e\n\x0c_transactionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bid_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BID._serialized_start=85
  _BID._serialized_end=283
# @@protoc_insertion_point(module_scope)
